import dynamic_continuum_models_systems_particles_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dynamic_continuum_models_systems_particles_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dynamic_continuum_models_systems_particles_theorem_canonical_lane_mathlib
end HautevilleHouse
